name: uvccamera
description: >
  A USB Video Class (UVC) camera plugin for Flutter based on UVCCamera library for Android.
  Fork of https://github.com/alexey-pelykh/UVCCamera by Alexey Pelykh.
version: 0.2.1
repository: https://github.com/jhionan/UVCCamera/tree/main/flutter
issue_tracker: https://github.com/jhionan/UVCCamera/issues
homepage: https://github.com/jhionan/UVCCamera
platforms:
  android:
  web:

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  cross_file: ^0.3.4+2
  copy_with_extension: ^12.1.0
  equatable: ^2.0.7
  web: ^1.1.0
  flutter_webhid: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.0
  copy_with_extension_gen: ^12.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.uvccamera.flutter
        pluginClass: UvcCameraPlugin
      web:
        pluginClass: UvcCameraWebPlatform
        fileName: src/uvccamera_web_platform.dart
